apiVersion: v1
kind: Secret
metadata:
  name: {{ include "workflow-engine.fullname" . }}-db
  labels:
    {{- include "workflow-engine.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.postgres.username | quote }}
  password: {{ include "workflow-engine.postgresPassword" . | quote }}
  database: {{ .Values.postgres.database | quote }}
  DATABASE_URL: {{ include "workflow-engine.databaseUrl" . | quote }}
