{{- if .Values.postgres.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "workflow-engine.postgresFullname" . }}
  labels:
    {{- include "workflow-engine.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: {{ .Values.postgres.port }}
      targetPort: postgres
  selector:
    {{- include "workflow-engine.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
{{- end -}}
